feat: make generating of execution numbers atomic
kubeshop/testkube pull request #1928
Opened 2022-07-27 16:45 UTC by nicufk

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2022-07-28 06:24 UTC, vsukhin requested changes
we need to add selector to Webhook CRD

2022-07-28 10:00 UTC, vsukhin reviewed
one question

2022-07-28 10:03 UTC, vsukhin reviewed
.

2022-08-01 05:26 UTC, exu commented on internal/pkg/api/repository/result/mongo.go
> +	CollectionNumbers = "numbers"
I would name it 'sequences'

2022-08-01 05:26 UTC, exu commented on internal/pkg/api/repository/result/interface.go
> +	GetNextExecutionNumber(ctx context.Context, testName string) (number int, err error)
I would close it in separate interface and add it here 

Additionally move out logic to separate structure to allow easy composition

2022-08-02 14:04 UTC, vsukhin approved these changes

2022-08-03 06:12 UTC, exu approved these changes

2022-08-03 07:56 UTC, merged