fix: delete execution numbers when test/testsuite is deleted
kubeshop/testkube pull request #3700
Opened 2023-04-18 17:42 UTC by nicufk

## Pull request description 

Close https://github.com/kubeshop/testkube/issues/3553

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-04-18 17:54 UTC, vsukhin commented on pkg/repository/result/mongo_numbers.go
> +	//_, err = r.SequencesColl.DeleteMany(context.Background(), filter)
Shouldit be removed on uncommented?

2023-04-18 17:55 UTC, vsukhin approved these changes
looks good, one question

2023-04-19 12:27 UTC, exu requested changes
it breaks cloud API. We need to plan and cooperate such change.

2023-04-19 14:16 UTC, exu approved these changes

2023-04-20 11:57 UTC, merged