ts sdk
kubeshop/testkube pull request #3860
Opened 2023-05-19 14:31 UTC by aabedraba

- feat: initial sdk version
- feat: publish package, create wrapper and create example

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-05-19 14:34 UTC, vsukhin approved these changes

2023-05-22 06:50 UTC, rangoo94 requested changes

2023-05-22 06:50 UTC, rangoo94 commented on sdk/src/generated-client.ts
> +/**
This generated code shouldn't be a part of GitHub repository, it should be `.gitignore`d.

Instead, you may add it to `"build"` script in NPM.

2023-05-22 06:50 UTC, rangoo94 commented on sdk/src/testkube.ts
> +  console.log("Testkube SDK initialized with url: ", url);
```suggestion
```

2023-05-22 06:50 UTC, rangoo94 commented on sdk/tsconfig.json
> +{
Could be cleaner to delete all comments there.

2023-05-22 06:50 UTC, rangoo94 commented on sdk/package.json
> +  },
There should be `build` script to build with `tsc` and generate client with `oazapfts`. Additionally, `prepublish` script should call it, so `npm publish` would build it correctly.

```suggestion
  "scripts": {
    "build": "oazapfts ../api/v1/testkube.yaml ./src/generated-client.ts && tsc",
    "prepublish": "npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

2023-05-22 06:50 UTC, rangoo94 commented on sdk/package.json
> +  "devDependencies": {},
`typescript` missing

2023-05-22 06:50 UTC, rangoo94 commented on sdk/src/testkube.ts
> +export const test = (name: string) => {
Is that actually used?

2023-05-22 06:50 UTC, rangoo94 commented on sdk/.gitignore
> +node_modules
Missing empty line at the end, and `src/generated-client.ts`

2023-05-22 06:50 UTC, rangoo94 commented on sdk/example/src/index.ts
> +const main = async () => {
Probably it's better to add information in the `README.md` file how to use it, instead of the example package.

2023-12-22 09:50 UTC, closed without merging