docs: updated getting started section for cloud
kubeshop/testkube pull request #4023
Opened 2023-06-12 18:00 UTC by alelthomas

## Pull request description 
updated step 2 of getting started docs

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [x] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-06-12 19:55 UTC, aabedraba requested changes

2023-06-12 19:55 UTC, aabedraba commented on docs/docs/articles/step2-installing-agent.md
> +# Step 2 - Installing the Testkube Agent
the instruction here is for creating another environment, but free accounts can only have 1 env max: https://testkube.io/pricing

Can you please do the instruction for when someone is creating a new account completely (to simulate that, just create a new org and you'll have the welcome page).

2023-06-12 19:55 UTC, aabedraba commented on docs/sidebars.js
> +        "articles/step2-installing-agent",
let's not just change the url for now, please, this will have cascading effects.. 
happy to keep it as cluster-components

2023-06-12 20:05 UTC, alelthomas commented
What do I do with this section btw?
![CleanShot 2023-06-12 at 16 04 47](https://github.com/kubeshop/testkube/assets/93217218/131e5e82-7934-4f9f-aad0-3748034a29bc)

2023-06-13 01:40 UTC, aabedraba commented on docs/docs/index.mdx
> +- 🧑‍💻 Manually via Testkube's CLI or via Testkube's Dashboard
👍🏽

2023-06-13 01:40 UTC, aabedraba approved these changes

2023-06-13 13:15 UTC, jfermi commented on docs/docs/articles/step2-installing-cluster-components.md
> +- To install `helm` just follow the [install instrcutions on the Helm web site](https://helm.sh/docs/intro/install/).
```suggestion
- To install `helm` just follow the [install instructions on the Helm web site](https://helm.sh/docs/intro/install/).
```

2023-06-13 13:16 UTC, jfermi reviewed
One spelling correction.

2023-06-14 06:17 UTC, merged