feat:[WIP] Add delete command and endpoint.
kubeshop/testkube pull request #463
Opened 2021-11-01 09:12 UTC by nicufk

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2021-11-01 09:44 UTC, jasmingacic approved these changes
looks legit

2021-11-01 11:54 UTC, hamzahsn approved these changes

2021-11-02 05:30 UTC, exu requested changes

2021-11-02 08:49 UTC, nicufk commented on pkg/api/v1/client/direct.go
> +	client *http.Client
Done!

2021-11-02 09:17 UTC, exu approved these changes

2021-11-02 09:20 UTC, merged