added the pushing latest tag to the release
kubeshop/testkube pull request #4672
Opened 2023-11-23 20:48 UTC by emamihe

## Pull request description 

This PR will cover adding the latest image tag to kubeshop/testkube-cli

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-11-23 20:49 UTC, vsukhin approved these changes

2023-11-23 22:04 UTC, dejanzele requested changes

2023-11-23 22:04 UTC, dejanzele commented on .github/workflows/release.yaml
> +          # adding the docker manifest for the latest image tag
This should be handled in `.builds-linux.goreleaser.yml` and this whole step can be removed.

We already build and push images in the previous step when running `goreleaser release`, this pushes the same images again.

Here is the respective GoReleaser config https://github.com/kubeshop/testkube/blob/develop/.builds-linux.goreleaser.yml#L56-L81

2023-11-24 09:50 UTC, dejanzele approved these changes

2023-11-24 09:52 UTC, merged