added segmentio telemetry
kubeshop/testkube pull request #475
Opened 2021-11-04 19:01 UTC by jasmingacic

Added data anonymous data collection.  Basically it collects information about the host in form like this:
```
{
  "anonymousId": "a4652358effb311a074bf84d2aed5a7d270dee858bff10e847df2a9ea132bb38",
  "context": {
    "library": {
      "name": "analytics-go",
      "version": "3.0.0"
    }
  },
  "event": "testkube-heartbeat",
  "integrations": {},
  "messageId": "2021-11-04 19:54:40.029549 +0100 CET m=+0.148209228",
  "originalTimestamp": "2021-11-04T19:54:40.029571+01:00",
  "receivedAt": "2021-11-04T18:54:41.004Z",
  "sentAt": "2021-11-04T18:54:40.029Z",
  "timestamp": "2021-11-04T18:54:41.004Z",
  "type": "track"
}
```

If we are going to proceed with this we need to make sure that LD_FLAG is passed 
```
LD_FLAGS += -X github.com/kubeshop/testkube/pkg/telemetry.telemetryToken=$(TELEMETRY_TOKEN)
```

Also `TESTKUBE_TELEMETRY_DISABLE` can be passed to the API server to disable data collection.

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

2021-11-04 20:07 UTC, exu commented
Ldflags are added only in makefile 
I think we have also some docker bake commands in GitHub action so probably it'll need to added there also ?

2021-11-04 20:14 UTC, exu commented
Do we want to embed key in binary ? I think it'll be quite easy to retrieve

2021-11-04 20:15 UTC, exu commented
Missing docs describing what kind of data are we sending and how to disable it on demand

2021-11-04 20:32 UTC, jasmingacic commented
Let's find the best options for deployment and I will add docs. Open questions are how the users will be able to opt out of telemetry.

Embedding the key into the app is the easiest way plus even if we exposed it no harm done. Also let's see what @fog1985 suggests on how to add that to GH actions

2021-11-05 08:04 UTC, exu requested changes

2021-11-05 09:07 UTC, jasmingacic commented on cmd/api-server/main.go
> +	if _, telemetryNotEnabled := os.LookupEnv("TESTKUBE_TELEMETRY_DISABLED"); !telemetryNotEnabled {
by default it is enabled, unless you specify otherwise
we want to get as much data as possible

2021-11-08 09:13 UTC, exu requested changes
still missing docs

2021-11-08 11:50 UTC, fog1985 commented
> Let's find the best options for deployment and I will add docs. Open questions are how the users will be able to opt out of telemetry.
> 
> Embedding the key into the app is the easiest way plus even if we exposed it no harm done. Also let's see what @fog1985 suggests on how to add that to GH actions

Hey @jasmingacic ,
Not sure what is meant to be done on GH's side. Please clarify so that I could respond. properly.

2021-11-08 12:00 UTC, jasmingacic commented
@fog1985 so when we bake our release we should inject [LD_FLAG](https://github.com/kubeshop/testkube/blob/telemetry/Makefile#L10) which is passed to build [process](https://github.com/kubeshop/testkube/blob/telemetry/Makefile#L25) the value of LD_FLAG should be stored as a secret somewhere in GH actions.

2021-11-08 12:19 UTC, olensmar commented on docs/telemetry.md
> +Telemetry collects and scrambles infromation about the host when the API server is bootstrapped for the first time.
", allowing us to ... " ?

2021-11-08 13:16 UTC, olensmar commented on docs/telemetry.md
> +Telemetry collects and scrambles infromation about the host when the API server is bootstrapped for the first time.
typo - infromation

2021-11-08 14:11 UTC, exu approved these changes

2021-11-08 14:11 UTC, merged