added tags to script model
kubeshop/testkube pull request #651
Opened 2021-12-15 12:04 UTC by jasmingacic

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

## Pull request description 

Just the model and API definition

Fixes #623 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2021-12-15 13:04 UTC, exu requested changes

2021-12-15 13:04 UTC, exu commented on api/v1/testkube.yaml
> +        - in: query
make it reference

2021-12-15 13:04 UTC, exu commented on api/v1/testkube.yaml
> +      parameters:
use ref

2021-12-20 13:01 UTC, jasmingacic commented on api/v1/testkube.yaml
> +          description: test tags
```suggestion
          description: script tags
```

2021-12-20 13:01 UTC, jasmingacic commented on api/v1/testkube.yaml
> +          description: test tags
```suggestion
          description: test execution tags
```

2021-12-20 13:01 UTC, jasmingacic commented on api/v1/testkube.yaml
> +          description: test tags
```suggestion
          description: execution tags
```

2021-12-20 15:44 UTC, exu approved these changes

2021-12-21 08:43 UTC, fog1985 approved these changes
LGTM

2021-12-21 10:19 UTC, merged